#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Topeka.Resource", IsApplication=true)]

namespace Topeka
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::Topeka.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::Topeka.Resource.String.Hello;
		}
		
		public partial class Animator
		{
			
			// aapt resource value: 0x7f050000
			public const int cross_to_tick_line_1 = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int cross_to_tick_line_2 = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int rotate_cross_to_tick = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int rotate_tick_to_cross = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int slide_in_bottom = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int slide_out_top = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int tick_to_cross_line_1 = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int tick_to_cross_line_2 = 2131034119;
			
			static Animator()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animator()
			{
			}
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0d0000
			public const int alphabet = 2131558400;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f0b0000
			public const int cardview_dark_background = 2131427328;
			
			// aapt resource value: 0x7f0b0001
			public const int cardview_light_background = 2131427329;
			
			// aapt resource value: 0x7f0b0002
			public const int cardview_shadow_end_color = 2131427330;
			
			// aapt resource value: 0x7f0b0003
			public const int cardview_shadow_start_color = 2131427331;
			
			// aapt resource value: 0x7f0b0024
			public const int green = 2131427364;
			
			// aapt resource value: 0x7f0b0026
			public const int light_grey = 2131427366;
			
			// aapt resource value: 0x7f0b0025
			public const int red = 2131427365;
			
			// aapt resource value: 0x7f0b000a
			public const int text_dark = 2131427338;
			
			// aapt resource value: 0x7f0b0009
			public const int text_light = 2131427337;
			
			// aapt resource value: 0x7f0b000d
			public const int theme_blue_accent = 2131427341;
			
			// aapt resource value: 0x7f0b000b
			public const int theme_blue_background = 2131427339;
			
			// aapt resource value: 0x7f0b000c
			public const int theme_blue_primary = 2131427340;
			
			// aapt resource value: 0x7f0b000f
			public const int theme_blue_primary_dark = 2131427343;
			
			// aapt resource value: 0x7f0b000e
			public const int theme_blue_text = 2131427342;
			
			// aapt resource value: 0x7f0b0012
			public const int theme_green_accent = 2131427346;
			
			// aapt resource value: 0x7f0b0010
			public const int theme_green_background = 2131427344;
			
			// aapt resource value: 0x7f0b0011
			public const int theme_green_primary = 2131427345;
			
			// aapt resource value: 0x7f0b0014
			public const int theme_green_primary_dark = 2131427348;
			
			// aapt resource value: 0x7f0b0013
			public const int theme_green_text = 2131427347;
			
			// aapt resource value: 0x7f0b0017
			public const int theme_purple_accent = 2131427351;
			
			// aapt resource value: 0x7f0b0015
			public const int theme_purple_background = 2131427349;
			
			// aapt resource value: 0x7f0b0016
			public const int theme_purple_primary = 2131427350;
			
			// aapt resource value: 0x7f0b0019
			public const int theme_purple_primary_dark = 2131427353;
			
			// aapt resource value: 0x7f0b0018
			public const int theme_purple_text = 2131427352;
			
			// aapt resource value: 0x7f0b001c
			public const int theme_red_accent = 2131427356;
			
			// aapt resource value: 0x7f0b001a
			public const int theme_red_background = 2131427354;
			
			// aapt resource value: 0x7f0b001b
			public const int theme_red_primary = 2131427355;
			
			// aapt resource value: 0x7f0b001e
			public const int theme_red_primary_dark = 2131427358;
			
			// aapt resource value: 0x7f0b001d
			public const int theme_red_text = 2131427357;
			
			// aapt resource value: 0x7f0b0021
			public const int theme_yellow_accent = 2131427361;
			
			// aapt resource value: 0x7f0b001f
			public const int theme_yellow_background = 2131427359;
			
			// aapt resource value: 0x7f0b0020
			public const int theme_yellow_primary = 2131427360;
			
			// aapt resource value: 0x7f0b0023
			public const int theme_yellow_primary_dark = 2131427363;
			
			// aapt resource value: 0x7f0b0022
			public const int theme_yellow_text = 2131427362;
			
			// aapt resource value: 0x7f0b0027
			public const int tick_cross_stroke_color = 2131427367;
			
			// aapt resource value: 0x7f0b0008
			public const int topeka_accent = 2131427336;
			
			// aapt resource value: 0x7f0b0007
			public const int topeka_blank = 2131427335;
			
			// aapt resource value: 0x7f0b0005
			public const int topeka_primary = 2131427333;
			
			// aapt resource value: 0x7f0b0006
			public const int topeka_primary_dark = 2131427334;
			
			// aapt resource value: 0x7f0b0004
			public const int touch_effect = 2131427332;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080003
			public const int cardview_compat_inset_shadow = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int cardview_default_elevation = 2131230724;
			
			// aapt resource value: 0x7f080005
			public const int cardview_default_radius = 2131230725;
			
			// aapt resource value: 0x7f08000e
			public const int elevation_fab = 2131230734;
			
			// aapt resource value: 0x7f08000d
			public const int elevation_header = 2131230733;
			
			// aapt resource value: 0x7f080000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int item_touch_helper_swipe_escape_max_velocity = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int item_touch_helper_swipe_escape_velocity = 2131230722;
			
			// aapt resource value: 0x7f080010
			public const int min_height_question = 2131230736;
			
			// aapt resource value: 0x7f08000f
			public const int min_height_touch_target = 2131230735;
			
			// aapt resource value: 0x7f08000b
			public const int size_avatar_toolbar = 2131230731;
			
			// aapt resource value: 0x7f080012
			public const int size_edit_text = 2131230738;
			
			// aapt resource value: 0x7f08000a
			public const int size_fab = 2131230730;
			
			// aapt resource value: 0x7f08000c
			public const int size_score_mark = 2131230732;
			
			// aapt resource value: 0x7f080008
			public const int spacing_double = 2131230728;
			
			// aapt resource value: 0x7f080009
			public const int spacing_huge = 2131230729;
			
			// aapt resource value: 0x7f080006
			public const int spacing_micro = 2131230726;
			
			// aapt resource value: 0x7f080007
			public const int spacing_normal = 2131230727;
			
			// aapt resource value: 0x7f080011
			public const int stroke_width_avatar = 2131230737;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int answer_quiz_fab = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int avatar_1 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int avatar_10 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int avatar_10_raster = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int avatar_11 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int avatar_11_raster = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int avatar_12 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int avatar_12_raster = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int avatar_13 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int avatar_13_raster = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int avatar_14 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int avatar_14_raster = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int avatar_15 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int avatar_15_raster = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int avatar_16 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int avatar_16_raster = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int avatar_1_raster = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int avatar_2 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int avatar_2_raster = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int avatar_3 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int avatar_3_raster = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int avatar_4 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int avatar_4_raster = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int avatar_5 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int avatar_5_raster = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int avatar_6 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int avatar_6_raster = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int avatar_7 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int avatar_7_raster = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int avatar_8 = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int avatar_8_raster = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int avatar_9 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int avatar_9_raster = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int avd_cross_to_tick = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int avd_tick_to_cross = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int fab_background = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_arrow_back = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_cross = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_play = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_tick = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_category_entertainment = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_category_entertainment_raster = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_category_food = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_category_food_raster = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int icon_category_geography = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int icon_category_geography_raster = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int icon_category_history = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int icon_category_history_raster = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int icon_category_knowledge = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int icon_category_knowledge_raster = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int icon_category_leaderboard = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int icon_category_leaderboard_raster = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int icon_category_music = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int icon_category_music_raster = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int icon_category_science = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int icon_category_science_raster = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int icon_category_sports = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int icon_category_sports_raster = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int icon_category_tvmovies = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int icon_category_tvmovies_raster = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int image_category_entertainment = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int image_category_entertainment_raster = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int image_category_food = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int image_category_food_raster = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int image_category_geography = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int image_category_geography_raster = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int image_category_history = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int image_category_history_raster = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int image_category_knowledge = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int image_category_knowledge_raster = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int image_category_music = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int image_category_music_raster = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int image_category_science = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int image_category_science_raster = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int image_category_sports = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int image_category_sports_raster = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int image_category_tvmovies = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int image_category_tvmovies_raster = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ripple = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int selector_avatar = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int selector_button = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int selector_checkable = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int selector_false = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int selector_true = 2130837588;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090002
			public const int absQuizViewContainer = 2131296258;
			
			// aapt resource value: 0x7f09001c
			public const int answer = 2131296284;
			
			// aapt resource value: 0x7f090024
			public const int answerFalse = 2131296292;
			
			// aapt resource value: 0x7f090023
			public const int answerTrue = 2131296291;
			
			// aapt resource value: 0x7f090006
			public const int avatar = 2131296262;
			
			// aapt resource value: 0x7f090026
			public const int avatars = 2131296294;
			
			// aapt resource value: 0x7f090011
			public const int categories = 2131296273;
			
			// aapt resource value: 0x7f090018
			public const int category_icon = 2131296280;
			
			// aapt resource value: 0x7f090019
			public const int category_title = 2131296281;
			
			// aapt resource value: 0x7f090017
			public const int content = 2131296279;
			
			// aapt resource value: 0x7f09002a
			public const int correct = 2131296298;
			
			// aapt resource value: 0x7f090010
			public const int done = 2131296272;
			
			// aapt resource value: 0x7f090016
			public const int empty = 2131296278;
			
			// aapt resource value: 0x7f090020
			public const int end = 2131296288;
			
			// aapt resource value: 0x7f09000b
			public const int fab_quiz = 2131296267;
			
			// aapt resource value: 0x7f090028
			public const int first_name = 2131296296;
			
			// aapt resource value: 0x7f09000d
			public const int icon = 2131296269;
			
			// aapt resource value: 0x7f09002b
			public const int incorrect = 2131296299;
			
			// aapt resource value: 0x7f090000
			public const int item_touch_helper_previous_elevation = 2131296256;
			
			// aapt resource value: 0x7f090029
			public const int last_initial = 2131296297;
			
			// aapt resource value: 0x7f09000a
			public const int progress = 2131296266;
			
			// aapt resource value: 0x7f090015
			public const int progress_text = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int progress_toolbar = 2131296276;
			
			// aapt resource value: 0x7f09001d
			public const int question_view = 2131296285;
			
			// aapt resource value: 0x7f09001b
			public const int quiz = 2131296283;
			
			// aapt resource value: 0x7f090009
			public const int quiz_container = 2131296265;
			
			// aapt resource value: 0x7f090003
			public const int quiz_content = 2131296259;
			
			// aapt resource value: 0x7f090004
			public const int quiz_done = 2131296260;
			
			// aapt resource value: 0x7f09001e
			public const int quiz_edit_text = 2131296286;
			
			// aapt resource value: 0x7f09000e
			public const int quiz_fragment_container = 2131296270;
			
			// aapt resource value: 0x7f090013
			public const int quiz_view = 2131296275;
			
			// aapt resource value: 0x7f090008
			public const int score = 2131296264;
			
			// aapt resource value: 0x7f090012
			public const int scorecard = 2131296274;
			
			// aapt resource value: 0x7f090022
			public const int seekbar = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int seekbar_progress = 2131296289;
			
			// aapt resource value: 0x7f09000f
			public const int sign_in_container = 2131296271;
			
			// aapt resource value: 0x7f09002c
			public const int sign_out = 2131296300;
			
			// aapt resource value: 0x7f09001a
			public const int solved_state = 2131296282;
			
			// aapt resource value: 0x7f09001f
			public const int start = 2131296287;
			
			// aapt resource value: 0x7f090001
			public const int submitAnswer = 2131296257;
			
			// aapt resource value: 0x7f090007
			public const int title = 2131296263;
			
			// aapt resource value: 0x7f09000c
			public const int toolbar_activity_quiz = 2131296268;
			
			// aapt resource value: 0x7f090025
			public const int toolbar_choose_avatar = 2131296293;
			
			// aapt resource value: 0x7f090005
			public const int toolbar_player = 2131296261;
			
			// aapt resource value: 0x7f090027
			public const int toolbar_sign_in = 2131296295;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f0e0005
			public const int duration = 2131623941;
			
			// aapt resource value: 0x7f0e0004
			public const int tick_cross_stroke_width = 2131623940;
			
			// aapt resource value: 0x7f0e0002
			public const int viewport_center_x = 2131623938;
			
			// aapt resource value: 0x7f0e0003
			public const int viewport_center_y = 2131623939;
			
			// aapt resource value: 0x7f0e0001
			public const int viewport_height = 2131623937;
			
			// aapt resource value: 0x7f0e0000
			public const int viewport_width = 2131623936;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int activity_category_selection = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int activity_quiz = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int activity_sign_in = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int fab_done = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int fragment_categories = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int fragment_quiz = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int fragment_sign_in = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int item_answer = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int item_answer_start = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int item_avatar = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int item_category = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int item_scorecard = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int question = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int quiz_edit_text = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int quiz_fill_blank_with_surroundings = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int quiz_layout_picker = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int quiz_radio_group_true_false = 2130968592;
			
			// aapt resource value: 0x7f040011
			public const int sign_in_avatars = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int sign_in_username = 2130968594;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0f0000
			public const int menu_category = 2131689472;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int ic_launcher = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f070000
			public const int categories = 2131165184;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f0c0001
			public const int ApplicationName = 2131492865;
			
			// aapt resource value: 0x7f0c0000
			public const int Hello = 2131492864;
			
			// aapt resource value: 0x7f0c0007
			public const int an_avatar = 2131492871;
			
			// aapt resource value: 0x7f0c0002
			public const int app_name = 2131492866;
			
			// aapt resource value: 0x7f0c000b
			public const int btn_false = 2131492875;
			
			// aapt resource value: 0x7f0c000a
			public const int btn_true = 2131492874;
			
			// aapt resource value: 0x7f0c000c
			public const int category = 2131492876;
			
			// aapt resource value: 0x7f0c0006
			public const int choose_avatar = 2131492870;
			
			// aapt resource value: 0x7f0c0004
			public const int first_name = 2131492868;
			
			// aapt resource value: 0x7f0c0014
			public const int groupTickCross = 2131492884;
			
			// aapt resource value: 0x7f0c0003
			public const int last_initial = 2131492867;
			
			// aapt resource value: 0x7f0c0015
			public const int line_1 = 2131492885;
			
			// aapt resource value: 0x7f0c0016
			public const int line_2 = 2131492886;
			
			// aapt resource value: 0x7f0c0012
			public const int path_cross_line_1 = 2131492882;
			
			// aapt resource value: 0x7f0c0013
			public const int path_cross_line_2 = 2131492883;
			
			// aapt resource value: 0x7f0c0010
			public const int path_tick_line_1 = 2131492880;
			
			// aapt resource value: 0x7f0c0011
			public const int path_tick_line_2 = 2131492881;
			
			// aapt resource value: 0x7f0c0008
			public const int player_display_name = 2131492872;
			
			// aapt resource value: 0x7f0c0009
			public const int quiz_of_quizzes = 2131492873;
			
			// aapt resource value: 0x7f0c0005
			public const int sign_in = 2131492869;
			
			// aapt resource value: 0x7f0c000d
			public const int sign_out = 2131492877;
			
			// aapt resource value: 0x7f0c0017
			public const int transition_avatar = 2131492887;
			
			// aapt resource value: 0x7f0c0018
			public const int transition_background = 2131492888;
			
			// aapt resource value: 0x7f0c0019
			public const int transition_toolbar = 2131492889;
			
			// aapt resource value: 0x7f0c000e
			public const int up = 2131492878;
			
			// aapt resource value: 0x7f0c000f
			public const int x_points = 2131492879;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0001
			public const int Base_CardView = 2131361793;
			
			// aapt resource value: 0x7f0a0000
			public const int CardView = 2131361792;
			
			// aapt resource value: 0x7f0a0002
			public const int CardView_Dark = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int CardView_Light = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int Topeka = 2131361796;
			
			// aapt resource value: 0x7f0a0006
			public const int Topeka_Blue = 2131361798;
			
			// aapt resource value: 0x7f0a0005
			public const int Topeka_CategorySelectionActivity = 2131361797;
			
			// aapt resource value: 0x7f0a000b
			public const int Topeka_CompoundButton = 2131361803;
			
			// aapt resource value: 0x7f0a000e
			public const int Topeka_CompoundButton_False = 2131361806;
			
			// aapt resource value: 0x7f0a000c
			public const int Topeka_CompoundButton_Radio = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int Topeka_CompoundButton_True = 2131361805;
			
			// aapt resource value: 0x7f0a0007
			public const int Topeka_Green = 2131361799;
			
			// aapt resource value: 0x7f0a0008
			public const int Topeka_Purple = 2131361800;
			
			// aapt resource value: 0x7f0a0009
			public const int Topeka_Red = 2131361801;
			
			// aapt resource value: 0x7f0a000f
			public const int Topeka_TextAppearance = 2131361807;
			
			// aapt resource value: 0x7f0a0013
			public const int Topeka_TextAppearance_Subhead = 2131361811;
			
			// aapt resource value: 0x7f0a0010
			public const int Topeka_TextAppearance_Title = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int Topeka_TextAppearance_Title_Inverse = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int Topeka_TextAppearance_Title_Picker = 2131361810;
			
			// aapt resource value: 0x7f0a000a
			public const int Topeka_Yellow = 2131361802;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Transition
		{
			
			// aapt resource value: 0x7f060000
			public const int category_enter = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int quiz_enter = 2131099649;
			
			static Transition()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Transition()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
