#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyList.Resource", IsApplication=true)]

namespace MyList
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040020
			public const int green = 2130968608;
			
			// aapt resource value: 0x7f040022
			public const int light_grey = 2130968610;
			
			// aapt resource value: 0x7f040021
			public const int red = 2130968609;
			
			// aapt resource value: 0x7f040006
			public const int text_dark = 2130968582;
			
			// aapt resource value: 0x7f040005
			public const int text_light = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int theme_blue_accent = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int theme_blue_background = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int theme_blue_primary = 2130968584;
			
			// aapt resource value: 0x7f04000b
			public const int theme_blue_primary_dark = 2130968587;
			
			// aapt resource value: 0x7f04000a
			public const int theme_blue_text = 2130968586;
			
			// aapt resource value: 0x7f04000e
			public const int theme_green_accent = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int theme_green_background = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int theme_green_primary = 2130968589;
			
			// aapt resource value: 0x7f040010
			public const int theme_green_primary_dark = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int theme_green_text = 2130968591;
			
			// aapt resource value: 0x7f040013
			public const int theme_purple_accent = 2130968595;
			
			// aapt resource value: 0x7f040011
			public const int theme_purple_background = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int theme_purple_primary = 2130968594;
			
			// aapt resource value: 0x7f040015
			public const int theme_purple_primary_dark = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int theme_purple_text = 2130968596;
			
			// aapt resource value: 0x7f040018
			public const int theme_red_accent = 2130968600;
			
			// aapt resource value: 0x7f040016
			public const int theme_red_background = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int theme_red_primary = 2130968599;
			
			// aapt resource value: 0x7f04001a
			public const int theme_red_primary_dark = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int theme_red_text = 2130968601;
			
			// aapt resource value: 0x7f04001d
			public const int theme_yellow_accent = 2130968605;
			
			// aapt resource value: 0x7f04001b
			public const int theme_yellow_background = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int theme_yellow_primary = 2130968604;
			
			// aapt resource value: 0x7f04001f
			public const int theme_yellow_primary_dark = 2130968607;
			
			// aapt resource value: 0x7f04001e
			public const int theme_yellow_text = 2130968606;
			
			// aapt resource value: 0x7f040023
			public const int tick_cross_stroke_color = 2130968611;
			
			// aapt resource value: 0x7f040004
			public const int topeka_accent = 2130968580;
			
			// aapt resource value: 0x7f040003
			public const int topeka_blank = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int topeka_primary = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int topeka_primary_dark = 2130968578;
			
			// aapt resource value: 0x7f040000
			public const int touch_effect = 2130968576;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050008
			public const int elevation_fab = 2131034120;
			
			// aapt resource value: 0x7f050007
			public const int elevation_header = 2131034119;
			
			// aapt resource value: 0x7f05000a
			public const int min_height_question = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int min_height_touch_target = 2131034121;
			
			// aapt resource value: 0x7f050005
			public const int size_avatar_toolbar = 2131034117;
			
			// aapt resource value: 0x7f05000c
			public const int size_edit_text = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int size_fab = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int size_score_mark = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int spacing_double = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int spacing_huge = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int spacing_micro = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int spacing_normal = 2131034113;
			
			// aapt resource value: 0x7f05000b
			public const int stroke_width_avatar = 2131034123;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int avatar_1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int avatar_10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int avatar_10_raster = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int avatar_11 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int avatar_11_raster = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int avatar_12 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int avatar_12_raster = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int avatar_13 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int avatar_13_raster = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int avatar_14 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int avatar_14_raster = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int avatar_15 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int avatar_15_raster = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int avatar_16 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int avatar_16_raster = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int avatar_1_raster = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int avatar_2 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int avatar_2_raster = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int avatar_3 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int avatar_3_raster = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int avatar_4 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int avatar_4_raster = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int avatar_5 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int avatar_5_raster = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int avatar_6 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int avatar_6_raster = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int avatar_7 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int avatar_7_raster = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int avatar_8 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int avatar_8_raster = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int avatar_9 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int avatar_9_raster = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int fab_background = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_tick = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int Icon = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int icon_category_entertainment_raster = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int icon_category_food_raster = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int icon_category_geography_raster = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int icon_category_history_raster = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int icon_category_knowledge_raster = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int icon_category_leaderboard_raster = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int icon_category_music_raster = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int icon_category_science_raster = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int icon_category_sports_raster = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int icon_category_tvmovies_raster = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int image_category_entertainment_raster = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int image_category_food_raster = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int image_category_geography_raster = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int image_category_history_raster = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int image_category_knowledge_raster = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int image_category_music_raster = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int image_category_science_raster = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int image_category_sports_raster = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int image_category_tvmovies_raster = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int selector_avatar = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int selector_button = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int selector_checkable = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int selector_false = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int selector_true = 2130837562;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060009
			public const int MyButton = 2131099657;
			
			// aapt resource value: 0x7f060001
			public const int absQuizViewContainer = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int avatar = 2131099656;
			
			// aapt resource value: 0x7f06000c
			public const int avatars = 2131099660;
			
			// aapt resource value: 0x7f060007
			public const int content = 2131099655;
			
			// aapt resource value: 0x7f060005
			public const int done = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int empty = 2131099654;
			
			// aapt resource value: 0x7f06000e
			public const int first_name = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int last_initial = 2131099663;
			
			// aapt resource value: 0x7f060002
			public const int quiz_content = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int quiz_done = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int sign_in_container = 2131099652;
			
			// aapt resource value: 0x7f060000
			public const int submitAnswer = 2131099648;
			
			// aapt resource value: 0x7f06000a
			public const int textureView1 = 2131099658;
			
			// aapt resource value: 0x7f06000b
			public const int toolbar_choose_avatar = 2131099659;
			
			// aapt resource value: 0x7f06000d
			public const int toolbar_sign_in = 2131099661;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090005
			public const int duration = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int tick_cross_stroke_width = 2131296260;
			
			// aapt resource value: 0x7f090002
			public const int viewport_center_x = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int viewport_center_y = 2131296259;
			
			// aapt resource value: 0x7f090001
			public const int viewport_height = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int viewport_width = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_sign_in = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int fab_done = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int fragment_sign_in = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int item_avatar = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int layout1 = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Menu = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int sign_in_avatars = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int sign_in_username = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int ApplicationName = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int Hello = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int an_avatar = 2131165191;
			
			// aapt resource value: 0x7f070002
			public const int app_name = 2131165186;
			
			// aapt resource value: 0x7f07000b
			public const int btn_false = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int btn_true = 2131165194;
			
			// aapt resource value: 0x7f07000c
			public const int category = 2131165196;
			
			// aapt resource value: 0x7f070006
			public const int choose_avatar = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int first_name = 2131165188;
			
			// aapt resource value: 0x7f070014
			public const int groupTickCross = 2131165204;
			
			// aapt resource value: 0x7f070003
			public const int last_initial = 2131165187;
			
			// aapt resource value: 0x7f070015
			public const int line_1 = 2131165205;
			
			// aapt resource value: 0x7f070016
			public const int line_2 = 2131165206;
			
			// aapt resource value: 0x7f070012
			public const int path_cross_line_1 = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int path_cross_line_2 = 2131165203;
			
			// aapt resource value: 0x7f070010
			public const int path_tick_line_1 = 2131165200;
			
			// aapt resource value: 0x7f070011
			public const int path_tick_line_2 = 2131165201;
			
			// aapt resource value: 0x7f070008
			public const int player_display_name = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int quiz_of_quizzes = 2131165193;
			
			// aapt resource value: 0x7f070005
			public const int sign_in = 2131165189;
			
			// aapt resource value: 0x7f07000d
			public const int sign_out = 2131165197;
			
			// aapt resource value: 0x7f07000e
			public const int up = 2131165198;
			
			// aapt resource value: 0x7f07000f
			public const int x_points = 2131165199;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080000
			public const int Topeka = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Topeka_Blue = 2131230721;
			
			// aapt resource value: 0x7f080006
			public const int Topeka_CompoundButton = 2131230726;
			
			// aapt resource value: 0x7f080009
			public const int Topeka_CompoundButton_False = 2131230729;
			
			// aapt resource value: 0x7f080007
			public const int Topeka_CompoundButton_Radio = 2131230727;
			
			// aapt resource value: 0x7f080008
			public const int Topeka_CompoundButton_True = 2131230728;
			
			// aapt resource value: 0x7f080002
			public const int Topeka_Green = 2131230722;
			
			// aapt resource value: 0x7f080003
			public const int Topeka_Purple = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int Topeka_Red = 2131230724;
			
			// aapt resource value: 0x7f08000a
			public const int Topeka_TextAppearance = 2131230730;
			
			// aapt resource value: 0x7f08000e
			public const int Topeka_TextAppearance_Subhead = 2131230734;
			
			// aapt resource value: 0x7f08000b
			public const int Topeka_TextAppearance_Title = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int Topeka_TextAppearance_Title_Inverse = 2131230732;
			
			// aapt resource value: 0x7f08000d
			public const int Topeka_TextAppearance_Title_Picker = 2131230733;
			
			// aapt resource value: 0x7f080005
			public const int Topeka_Yellow = 2131230725;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
